<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\Build.props" />

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<!-- targets -->
	<PropertyGroup>
		<Configurations>Debug;Release;GoldMaster</Configurations>
		<DefineConstants Condition="'$(Configuration)' == 'GoldMaster|AnyCPU' ">TRACE;GOLDMASTER</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='GoldMaster'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<Optimize>true</Optimize>
		<PlatformTarget>AnyCPU</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="$(BepInExCore)/BepInEx.Core.dll" Private="false" />
		<Reference Include="$(BepInExCore)/BepInEx.Unity.IL2CPP.dll" Private="false" />
		<Reference Include="$(BepInExCore)/BepInEx.Unity.Common.dll" Private="false" />
		<Reference Include="$(BepInExCore)/0Harmony.dll" Private="false" />
		<Reference Include="$(BepInExCore)/SemanticVersioning.dll" Private="false" />
		<Reference Include="$(BepInExCore)/Il2CppInterop.Common.dll" Private="false" />
		<Reference Include="$(BepInExCore)/Il2CppInterop.Runtime.dll" Private="false" />
		<Reference Include="$(BepInExCore)/Il2CppInterop.HarmonySupport.dll" Private="false" />
		<Reference Include="$(Interop)/*.dll" Exclude="$(Interop)/__Generated.dll" Private="false" />
		<Reference Include="$(SptPlugins)/SPTushonka.*.dll" Private="false" />
		<Reference Include="$(FikaPlugins)/Fika.Core.dll" Private="false" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(OS)' == 'Windows_NT' ">
		<Exec Condition=" '$(Configuration)|$(Platform)' != 'GoldMaster|AnyCPU' " Command="call ../Properties/build/postbuild-core.bat &quot;$(TargetPath)&quot; &quot;$(ProjectDir)&quot;" />
	</Target>

</Project>
